### ISSUE TITLE
Error load dinamically slide 

### ISSUE THREAD

**Issue by areinoso** [denehyg/reveal.js-menu#11]
I have a function that load slides dinamically, like that

 Reveal.addEventListener( 'slidechanged', function( event ) {

```
    //var idPrevSlide =  event.previousSlide.id;
    //var prevSlide = $("#"+idPrevSlide);
    //prevSlide.html("");

    var idSlide = event.currentSlide.id;
    var slide = $("#"+idSlide);
    var settings = slide.data("settings");

    var data = jQuery.parseJSON(settings);

    if(data.tipo == 'texto'){
        slide.load("slides/texto/"+idSlide+".html");
    }

} ); 
```

But when I add menu.js to reveal, load don't works.
Also I had to change my function, because 'slide.data("settings")' return an string not an object (so I change to jQuery.parseJSON(settings)), but it only happens when I add menu.js.

**Comment by denehyg** [comment]
Reveal menu doesn't support changes to the slides after initialisation. An interim solution was implemented to delay the menu initialisation until explicitly called (see #37). Also, jquery didn't play nicely with the menu plugin as the ender library used overwrite the $ variable - this has now been fixed in dev (see #30).

I'm closing this for now as I expect you issue is covered in the others linked above. If you still have an issue feel free to reopen it.
