### ISSUE TITLE
Is there a simple way to keep the menu from sliding back to the left

### ISSUE THREAD

**Issue by NJseo** [denehyg/reveal.js-menu#25]
I picked up you platform and really am enjoying it. One thing I am having trouble with though is the menu as it keeps wanting to slide back to the left. Surely I could rediesign the all the li with different class names, but its such a good design. What I have used the left panel for is a form element editor, and every time I click in one of the forms, the menu disappears. Is there a simple way to prevent that?

**Comment by NJseo** [comment]
Additionally, I am using form elements in the main window as well. I was thinking it would be nice to prevent them from moving forward until they fill out the form element. Is there a way I can access that do that. Maybe a function call?

**Comment by denehyg** [comment]
I'm assuming that you are referring to clicking forms within the presentation, rather than in the menu. The menu has been designed to prevent interaction with the presentation while the menu is open. It adds an overlay when the menu is open so that when the user clicks the presentation area it is captured by the menu and the menu closes. So at present there is no way to interact with the presentation while the menu is open. I'll have a look at adding an option to remove this restriction.

**Comment by denehyg** [comment]
I'm closing this issue for now as I don't believe the use case fits the menu plugin. If there are others that think this would be useful I'll have another look.
