### ISSUE TITLE
Slidecahnged events don't trigger when using plugin

### ISSUE THREAD

**Issue by BartoszKop** [denehyg/reveal.js-menu#28]
I am using small jquery function to make a simple countup animation in my presentation but when I use menu plugin it suddenly stops to work and trigger only on the slide refresh but not when I change the slide. I tried to reslove the issue but without any luck. 

code:
```
	<script>
			 Reveal.addEventListener( 'slidechanged', function( event ) {
			 if(event.indexh == 5){
			 $('.count').each(function () {
					 $(this).prop('Counter',0).animate({
							 Counter: $(this).text()
					 }, {
							 duration: 3000,
							 easing: 'swing',
							 step: function () {
									 $(this).text(Math.ceil(this.Counter))
							 }
					 });
			 });
			}
			});
			</script>
```

**Comment by BartoszKop** [comment]
Issue solved by adding Jquery as dependency in async mode.

```
	dependencies: [
					{ src: 'plugin/extras/jquery.min.js', async: true},
```

**Comment by denehyg** [comment]
This is because I've used ender which uses the $ namespace, as does jquery. I expect that whichever library is loaded last is taking over $, prevent the other from working properly.

You should be able to use jquery still following this... https://learn.jquery.com/using-jquery-core/avoid-conflicts-other-libraries/

I'll look into how best to remove the conflict from within reveal.js-menu at some point in the future.
